# Simple Web Scraper Configuration
# Just list the sources you want to scrape

# Global settings
settings:
  output_file: "output.json"
  team_id: "aline123"
  pdf_directory: "Books_PDF"
  max_workers: 3
  request_delay: 0.2
  timeout: 15

# ZenRows API configuration (optional - for fallback scraping)
zenrows:
  enabled: true
  api_key: "api-key here"

# Sources to scrape - just URLs and basic info
sources:
  - name: "Interviewing.io Blog"
    url: "https://interviewing.io/blog"
    type: "blog"
    enabled: true

  - name: "Interviewing.io Guides"
    url: "https://interviewing.io/guides"
    type: "guides"
    enabled: true

  - name: "Interviewing.io Company Guides"
    url: "https://interviewing.io/topics#companies"
    type: "companies"
    enabled: true

  - name: "Interviewing.io Interview Guides"
    url: "https://interviewing.io/learn#interview-guides"
    type: "interview-guides"
    enabled: true

  - name: "Nil Mamano DSA Blog"
    url: "https://nilmamano.com/blog/category/dsa/"
    type: "blog"
    enabled: true

  - name: "Quill.co Blog"
    url: "https://quill.co/blog"
    type: "blog"
    enabled: true

  - name: "Shreycation Substack"
    url: "https://shreycation.substack.com"
    type: "newsletter"
    enabled: true

# Optional: Default fallback authors for sites where detection fails
# (Only used if no author can be detected automatically)
fallback_authors:
  "interviewing.io": "interviewing.io team"
  "nilmamano.com": "Nil Mamano"
  "quill.co": "Quill team"
  "shreycation.substack.com": "Shrey G" 